name: Deploy to OVH
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v6

      # Étape de Cache : accélère les futurs déploiements
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies (Composer)
        run: composer install --no-dev --optimize-autoloader

      - name: Sync via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./www/
          # On ignore Git, Node, et les dossiers persistants sur le serveur
          exclude: |
            **/.git*
            **/node_modules/**
            webroot/wordpress/**
            webroot/ns/**
            config/app_local.php
      - name: Trigger Migration
        run: |
          curl -f "https://ariaml.com/dev-ops/migrate?token=${{ secrets.MIGRATION_TOKEN }}"
